name: golang build

on: [push, pull_request, workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pinned toolchain
      uses: jdx/mise-action@v2

    - name: Build
      run: go build -v ./...

    - name: Lint
      run: golangci-lint run

    - name: Test
      run: go test -race -coverprofile=./coverage.txt -covermode=atomic ./...

    - name: Coverage gate
      run: go-test-coverage --config=.testcoverage.yml

    - name: Check goreleaser file
      run: goreleaser check
